### ISSUE TITLE
Increase docker swarm certificates validity date

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/nuvlabox-os#18]
The default is 3 months. What should be the new value ? 1/5/10 years ?

**Comment by cjdcordeiro** [comment]
I couldn't reproduce the faulty scenario where upon a machine reboot, the swarm certificates would not be renewed.

Nevertheless, I think it's find to increase the default validity for these certificates. I'd propose one of the following:

 - 6 months to 1 year validity, and let Docker rotate them when they expire
or 
 - 10 years validity, but implement a periodic task (in Nuvla or within the NuvlaBox system-manager), to force rotate them every 6 months

@schaubl feel free to create a new ticket with whatever option you feel is more secure/appropriate
