### ISSUE TITLE
Ensure system-manager doesn't kill NB Engine containers

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/nuvlabox-os#24]
Currently it do it if system requirement are not satisfied.
An environment variable can be defined to disable this check.

Maybe this check should be done only before/during the installation of the NB Engine (and before an update).

This require nuvlabox/nuvlabox#23.

**Comment by cjdcordeiro** [comment]
this can be closed as the system check only run at start and it does not cleanup any containers anymore (it sets the nb operational status to DEGRADED instead)
